# Generated by Django 6.1 on 2026-08-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("en-us", "English"), ("fr", "French")],
                default="en-us",
                help_text="Language the account is answered and written to in, whatever its browser asks for.",
                max_length=10,
            ),
        ),
    ]
