# Generated by Django 6.1 on 2026-08-19 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Household",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name given by the members, such as their family name.",
                        max_length=100,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the household was created, usually at the first member's signup.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HouseholdMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "Owner"), ("member", "Member")],
                        default="member",
                        help_text="Reserved for a later differentiation of rights: every member can do everything.",
                        max_length=10,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        help_text="Household the membership grants access to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="households.household",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Account granted access to the household, its people, its catalog and its trips.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("household", "user"),
                        name="unique_membership_per_household",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name shown in every picker asking who an item is for.",
                        max_length=100,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        help_text="Household the person belongs to, and outside of which they do not exist.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="persons",
                        to="households.household",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Account of the person when they have one, empty for a child or a guest.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="persons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("household", "user"),
                        name="unique_account_person_per_household",
                    )
                ],
            },
        ),
    ]
