# Generated by Django 6.1 on 2026-08-20 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("households", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="household",
            name="personal_of",
            field=models.OneToOneField(
                blank=True,
                help_text="Account this household is the private space of, empty when it is shared.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personal_household",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
