# Generated by Django 6.1 on 2026-08-21 01:45

import secrets

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("households", "0002_household_personal_of"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Address the invitation was sent to, which may or may not have an account.",
                        max_length=254,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=secrets.token_urlsafe,
                        help_text="Opaque secret carried by the link, never a guessable identifier.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the invitation was created and its email sent.",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When the token stops being accepted, a week after it was created."
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the invitation was accepted, which spends the single-use token.",
                        null=True,
                    ),
                ),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Account that accepted the invitation, which is not always the invited address.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        help_text="Shared household the invited address is offered membership of.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="households.household",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        help_text="Member who sent the invitation, emptied rather than cascading if they leave.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        help_text="Person the guest is expected to be, so accepting fills that person in.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitations",
                        to="households.person",
                    ),
                ),
            ],
        ),
    ]
