# Generated by Django 6.1 on 2026-08-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("households", "0003_invitation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="householdmember",
            name="role",
            field=models.CharField(
                choices=[("owner", "Owner"), ("member", "Member")],
                default="member",
                help_text="An owner invites, removes a member, renames and deletes the household; a member does the rest.",
                max_length=10,
            ),
        ),
    ]
