# Generated by Django 6.1 on 2026-08-25 07:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("households", "0004_alter_householdmember_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invitation",
            name="person",
        ),
    ]
