# Generated by Django 6.1 on 2026-08-24 19:00

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("households", "0004_alter_householdmember_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Wording shown on a line, such as taken out of the closet.",
                        max_length=100,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        help_text="Hexadecimal color the clients paint the status with, such as #f59e0b.",
                        max_length=7,
                    ),
                ),
                (
                    "progress",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("in_progress", "In progress"),
                            ("done", "Done"),
                        ],
                        default="not_started",
                        help_text="What the status counts as in the progress bar of a trip.",
                        max_length=11,
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        db_index=True,
                        editable=False,
                        help_text="Rank in the household status list, which also decides the default one.",
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        help_text="Household this preparation status belongs to, with its own wording.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_statuses",
                        to="households.household",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "item statuses",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="ItemType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="What the thing is called when picking it, such as bib or sandals.",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional details telling apart two entries that share a name.",
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        help_text="Household owning this entry of the catalog, which is never shared.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_types",
                        to="households.household",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Kit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="What the block is called, such as diaper bag or hiking gear.",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional reminder of what the block is meant to cover.",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        db_index=True,
                        editable=False,
                        help_text="Rank of the section the kit displays as in a trip.",
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        help_text="Household this reusable block belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kits",
                        to="households.household",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="KitItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="How many of the thing the block asks for, such as five t-shirts.",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Free reminder carried to the trip, such as the warm one.",
                        max_length=200,
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        db_index=True,
                        editable=False,
                        help_text="Rank in the block, which is the preparation order and follows into a trip.",
                    ),
                ),
                (
                    "item_type",
                    models.ForeignKey(
                        help_text="Catalog entry the line packs, taken from the same household.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kit_items",
                        to="catalog.itemtype",
                    ),
                ),
                (
                    "kit",
                    models.ForeignKey(
                        help_text="Block this line belongs to, and outside of which it does not exist.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="catalog.kit",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        help_text="Person the line is for, empty when it is for the whole household.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kit_items",
                        to="households.person",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.AddConstraint(
            model_name="itemtype",
            constraint=models.UniqueConstraint(
                models.F("household"),
                django.db.models.functions.text.Lower(django.db.models.functions.text.Trim("name")),
                name="unique_item_type_name_per_household",
            ),
        ),
    ]
