# Generated by Django 6.1 on 2026-08-27 15:36

from django.db import migrations, models


def make_the_first_status_of_each_household_the_default_one(apps, schema_editor):
    ItemStatus = apps.get_model("catalog", "ItemStatus")
    households = ItemStatus.objects.values_list("household_id", flat=True).distinct()
    for household_id in households:
        first = ItemStatus.objects.filter(household_id=household_id).order_by("position").first()
        ItemStatus.objects.filter(pk=first.pk).update(is_default=True)


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("households", "0005_remove_invitation_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemstatus",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Whether a new line gets this status, true for one status of the household.",
            ),
        ),
        migrations.AlterField(
            model_name="itemstatus",
            name="position",
            field=models.PositiveIntegerField(
                db_index=True,
                editable=False,
                help_text="Rank in the household status list.",
            ),
        ),
        migrations.RunPython(
            make_the_first_status_of_each_household_the_default_one,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="itemstatus",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("household",),
                name="unique_default_item_status_per_household",
            ),
        ),
    ]
