# Generated by Django 6.1 on 2026-08-28 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_itemstatus_is_default_alter_itemstatus_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kititem",
            name="quantity",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="How many of the thing the block asks for, such as five t-shirts.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(32767),
                ],
            ),
        ),
    ]
