# Generated by Django 6.1 on 2026-08-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_alter_kititem_quantity"),
        ("households", "0005_remove_invitation_person"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="kititem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)),
                name="kit_item_quantity_is_at_least_one",
            ),
        ),
    ]
