# Generated by Django 6.1 on 2026-08-31 08:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_kititem_kit_item_quantity_is_at_least_one"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kititem",
            name="note",
        ),
    ]
