# Generated by Django 6.1 on 2026-08-26 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("households", "0005_remove_invitation_person"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="What the trip is called, such as a week in Brittany.",
                        max_length=100,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Day the trip leaves on, which the trip list is sorted on."
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        help_text="Household preparing the trip, whose members share the same list.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to="households.household",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="TripItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="How many of the thing to pack, such as five t-shirts.",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Free reminder shown on the line, such as the warm one.",
                        max_length=200,
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        db_index=True,
                        editable=False,
                        help_text="Rank in the trip, taken from the kit at instantiation and editable afterwards.",
                    ),
                ),
                (
                    "item_type",
                    models.ForeignKey(
                        help_text="Catalog entry the line packs, taken from the same household.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_items",
                        to="catalog.itemtype",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        help_text="Person the line is for, empty when the thing is common or the person is gone.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trip_items",
                        to="households.person",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        help_text="Where the preparation of the line stands, which any member moves forward.",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="trip_items",
                        to="catalog.itemstatus",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        help_text="Trip this line belongs to, and outside of which it does not exist.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="TripParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        help_text="Person going on the trip, whose kit lines are the ones instantiated.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_participations",
                        to="households.person",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        help_text="Trip the person is going on.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="trips.trip",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="tripitem",
            constraint=models.UniqueConstraint(
                fields=("trip", "item_type", "person"), name="unique_trip_line_per_person"
            ),
        ),
        migrations.AddConstraint(
            model_name="tripitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("person__isnull", True)),
                fields=("trip", "item_type"),
                name="unique_common_trip_line",
            ),
        ),
        migrations.AddConstraint(
            model_name="tripparticipant",
            constraint=models.UniqueConstraint(
                fields=("trip", "person"), name="unique_participant_per_trip"
            ),
        ),
    ]
