# Generated by Django 6.1 on 2026-08-28 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_kititem_kit_item_quantity_is_at_least_one"),
        ("households", "0005_remove_invitation_person"),
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tripitem",
            name="quantity",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="How many of the thing to pack, such as five t-shirts.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(32767),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="tripitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)),
                name="trip_item_quantity_is_at_least_one",
            ),
        ),
    ]
