# Generated by Django 6.1 on 2026-08-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0002_alter_tripitem_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="archived_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When the trip left the current list, empty as long as it is still there.",
                null=True,
            ),
        ),
    ]
