# Generated by Django 6.1 on 2026-08-31 08:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0003_trip_archived_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tripitem",
            name="note",
        ),
    ]
