# Generated by Django 6.1 on 2026-08-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0004_remove_tripitem_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="tripitem",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="When the line last moved, which lets a client ask only for what changed.",
            ),
        ),
    ]
